#!/bin/sh
# Run by the model at the end of its reply, not by a hook: print this turn's staged
# coaching block on stdout so the model can echo it verbatim.
#
# Usage: collect.sh <session-id> <prompt-hash>
#
# The prefetch normally finishes long before the main task does, so this usually reads a
# file that is already there and returns instantly. The bounded wait only matters when
# the main task finished faster than the sidecar.
#
# POSIX sh only. Fail-open: always exit 0, print nothing when there is nothing to show.

SESSION=$1
HASH=$2
[ -n "$SESSION" ] && [ -n "$HASH" ] || exit 0

# Both values are used to build a path. They are generated by inject.sh, but this script
# is invoked through the model, so validate rather than trust.
case "$SESSION" in *[!a-zA-Z0-9-]* | '') exit 0 ;; esac
case "$HASH" in *[!a-f0-9]* | '') exit 0 ;; esac

RUN_DIR="$HOME/.claude/english-coach-data/sessions/$SESSION"
READY="$RUN_DIR/ready-$HASH"
PIDFILE="$RUN_DIR/pid-$HASH"

# 0.05s x 200 = 10s. Shorter than the old Stop-hook cap of 35s: by the time the model
# reaches this call the main task is already done, so any remaining wait is wait the
# user watches. A dead prefetch is detected in well under a second by the check below.
#
# `ps -p` rather than `kill -0`: kill reports EPERM as failure, so it calls any pid
# outside our own uid dead. That misread would abandon a live evaluation.
i=0
while [ ! -f "$READY" ] && [ "$i" -lt 200 ]; do
  if [ -f "$PIDFILE" ]; then
    PREFETCH_PID=$(cat "$PIDFILE" 2>/dev/null)
    case "$PREFETCH_PID" in
      '' | *[!0-9]*) break ;;
    esac
    ps -p "$PREFETCH_PID" >/dev/null 2>&1 || break
  elif [ "$i" -gt 60 ]; then
    # No pidfile after 3s: the prefetch never started (async dispatch dropped it,
    # config disabled between hooks) or it finished without staging a verdict. The
    # grace period covers a prefetch still forking its way to the pidfile write.
    break
  fi
  sleep 0.05
  i=$((i + 1))
done

[ -f "$READY" ] || exit 0
BLOCK=$(cat "$READY")
# Consume it, so a model that calls twice in one turn prints the block once.
rm -f "$READY" 2>/dev/null
[ -n "$BLOCK" ] || exit 0

printf '%s\n' "$BLOCK"
exit 0
